package orchestrator

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// CreatePRForIssue creates a pull request for a completed issue.
// Returns the PR URL if created, empty string if PR already exists, error on failure.
func CreatePRForIssue(issueNum int, issueTitle, branchName string, cfg *RunConfig) (string, error) {
	repo, _ := cfg.PrimaryRepo()
	if repo == nil {
		return "", fmt.Errorf("no primary repo configured")
	}

	// Check if PR already exists for this branch
	checkCmd := exec.Command("gh", "pr", "list", "--head", branchName, "--json", "url", "-q", ".[0].url")
	checkCmd.Dir = repo.Path
	if out, err := checkCmd.Output(); err == nil && strings.TrimSpace(string(out)) != "" {
		// PR already exists
		return "", nil
	}

	// Build PR title and body
	title := fmt.Sprintf("%s (#%d)", issueTitle, issueNum)
	if len(title) > 70 {
		title = title[:67] + "..."
	}

	body := fmt.Sprintf(`## Summary

Closes #%d

## Changes

See commit history for details.

---
🤖 Generated by orchestrator
`, issueNum)

	// Create the PR
	cmd := exec.Command("gh", "pr", "create",
		"--title", title,
		"--body", body,
		"--head", branchName,
	)
	cmd.Dir = repo.Path
	out, err := cmd.CombinedOutput()
	if err != nil {
		// Check if it's just "no commits" error (branch already merged or doesn't exist)
		if strings.Contains(string(out), "already exists") ||
			strings.Contains(string(out), "No commits") {
			return "", nil
		}
		return "", fmt.Errorf("gh pr create: %v: %s", err, string(out))
	}

	// Extract PR URL from output
	prURL := strings.TrimSpace(string(out))
	return prURL, nil
}

// MergeResult represents the outcome of a PR merge attempt.
type MergeResult struct {
	Success    bool
	PRNumber   int
	MergeError string
	Conflicts  bool
}

// MergePRForIssue attempts to merge a PR for a completed issue.
// Returns merge result with details about success or failure.
func MergePRForIssue(issueNum int, branchName string, cfg *RunConfig) MergeResult {
	repo, _ := cfg.PrimaryRepo()
	if repo == nil {
		return MergeResult{Success: false, MergeError: "no primary repo configured"}
	}

	// Get PR number for this branch
	prNum, err := GetPRNumberForBranch(branchName, repo.Path)
	if err != nil {
		return MergeResult{Success: false, MergeError: fmt.Sprintf("failed to get PR number: %v", err)}
	}
	if prNum == 0 {
		return MergeResult{Success: false, MergeError: "no PR found for branch"}
	}

	// Attempt to merge with squash (don't use --delete-branch as it fails with worktrees)
	cmd := exec.Command("gh", "pr", "merge", fmt.Sprintf("%d", prNum), "--squash")
	cmd.Dir = repo.Path
	out, err := cmd.CombinedOutput()
	outStr := string(out)

	if err != nil {
		// Check for merge conflicts
		if strings.Contains(outStr, "not mergeable") ||
			strings.Contains(outStr, "merge conflict") ||
			strings.Contains(outStr, "cannot be cleanly created") {
			return MergeResult{
				Success:    false,
				PRNumber:   prNum,
				MergeError: outStr,
				Conflicts:  true,
			}
		}
		return MergeResult{
			Success:    false,
			PRNumber:   prNum,
			MergeError: fmt.Sprintf("gh pr merge: %v: %s", err, outStr),
		}
	}

	// Delete remote branch separately (local branch stays for worktree)
	delCmd := exec.Command("git", "push", "origin", "--delete", branchName)
	delCmd.Dir = repo.Path
	if delOut, delErr := delCmd.CombinedOutput(); delErr != nil {
		// Log but don't fail - merge succeeded
		LogMsg(fmt.Sprintf("[merge] Warning: failed to delete remote branch %s: %s", branchName, string(delOut)))
	}

	LogMsg(fmt.Sprintf("[merge] Successfully merged PR #%d for issue #%d", prNum, issueNum))
	return MergeResult{Success: true, PRNumber: prNum}
}

// GetPRNumberForBranch returns the PR number for a given branch.
func GetPRNumberForBranch(branchName, repoPath string) (int, error) {
	cmd := exec.Command("gh", "pr", "list", "--head", branchName, "--json", "number", "-q", ".[0].number")
	cmd.Dir = repoPath
	out, err := cmd.Output()
	if err != nil {
		return 0, err
	}

	numStr := strings.TrimSpace(string(out))
	if numStr == "" {
		return 0, nil
	}

	var num int
	_, err = fmt.Sscanf(numStr, "%d", &num)
	return num, err
}

// ReopenIssueForMergeConflict reopens an issue when its PR has merge conflicts.
// It adds a comment explaining the conflict and what needs to be done.
func ReopenIssueForMergeConflict(issueNum int, branchName string, mergeError string, cfg *RunConfig) error {
	repo, _ := cfg.PrimaryRepo()
	if repo == nil {
		return fmt.Errorf("no primary repo configured")
	}

	// Reopen the issue
	cmd := exec.Command("gh", "issue", "reopen", fmt.Sprintf("%d", issueNum))
	cmd.Dir = repo.Path
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to reopen issue: %v: %s", err, string(out))
	}

	// Add a comment explaining the merge conflict
	comment := fmt.Sprintf(`## Merge Conflict

The PR for this issue has merge conflicts and could not be automatically merged.

**Branch:** `+"`%s`"+`

**Error:**
`+"```"+`
%s
`+"```"+`

**Action Required:**
1. Rebase the branch onto main: `+"`git fetch origin && git rebase origin/main`"+`
2. Resolve any conflicts
3. Push the updated branch: `+"`git push --force-with-lease`"+`
4. The orchestrator will retry the merge

---
🤖 Generated by orchestrator`, branchName, mergeError)

	commentCmd := exec.Command("gh", "issue", "comment", fmt.Sprintf("%d", issueNum), "--body", comment)
	commentCmd.Dir = repo.Path
	if out, err := commentCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to add comment: %v: %s", err, string(out))
	}

	LogMsg(fmt.Sprintf("[merge] Reopened issue #%d due to merge conflicts", issueNum))
	return nil
}

// PRLifecycleResult represents the outcome of the full PR lifecycle.
type PRLifecycleResult struct {
	PRCreated     bool
	PRURL         string
	Merged        bool
	MergeConflict bool
	IssueReopened bool
	RebaseAttempted bool
	RebaseSuccess   bool
	Error         error
}

// RebaseResult represents the outcome of a rebase attempt.
type RebaseResult struct {
	Success      bool
	Error        string
	HasConflicts bool
}

// RebaseBranchOntoMain attempts to rebase a branch onto the latest main/default branch.
// This is used when a PR has merge conflicts due to concurrent worker changes.
// Returns a RebaseResult indicating success or failure.
func RebaseBranchOntoMain(worktreePath, branchName, baseBranch string) RebaseResult {
	if baseBranch == "" {
		baseBranch = "main"
	}

	// Fetch latest from remote
	_, err := runGit(worktreePath, "fetch", "origin")
	if err != nil {
		return RebaseResult{Success: false, Error: fmt.Sprintf("fetch failed: %v", err)}
	}

	// Check if we're on the right branch
	currentBranch, err := runGit(worktreePath, "rev-parse", "--abbrev-ref", "HEAD")
	if err != nil {
		return RebaseResult{Success: false, Error: fmt.Sprintf("failed to get current branch: %v", err)}
	}
	currentBranch = strings.TrimSpace(currentBranch)

	// Checkout the branch if not already on it
	if currentBranch != branchName {
		_, err = runGit(worktreePath, "checkout", branchName)
		if err != nil {
			return RebaseResult{Success: false, Error: fmt.Sprintf("checkout failed: %v", err)}
		}
	}

	// Attempt the rebase
	baseRef := "origin/" + baseBranch
	out, err := runGit(worktreePath, "rebase", baseRef)
	if err != nil {
		outStr := string(out)
		// Check if there are conflicts that need manual resolution
		if strings.Contains(outStr, "CONFLICT") || strings.Contains(outStr, "conflict") {
			// Abort the rebase to leave the worktree in a clean state
			runGit(worktreePath, "rebase", "--abort")
			return RebaseResult{Success: false, HasConflicts: true, Error: "rebase has conflicts requiring manual resolution"}
		}
		// Try to abort any in-progress rebase
		runGit(worktreePath, "rebase", "--abort")
		return RebaseResult{Success: false, Error: fmt.Sprintf("rebase failed: %v: %s", err, outStr)}
	}

	LogMsg(fmt.Sprintf("[rebase] Successfully rebased %s onto %s", branchName, baseRef))
	return RebaseResult{Success: true}
}

// ForcePushBranch force-pushes a branch to the remote.
// Uses --force-with-lease for safety (will fail if remote has unexpected changes).
func ForcePushBranch(worktreePath, remote, branchName string) error {
	if remote == "" {
		remote = "origin"
	}

	out, err := runGit(worktreePath, "push", "--force-with-lease", remote, branchName)
	if err != nil {
		return fmt.Errorf("force push failed: %v: %s", err, out)
	}

	LogMsg(fmt.Sprintf("[push] Force pushed %s to %s", branchName, remote))
	return nil
}

// RebaseAndRetry attempts to rebase a branch and retry the merge.
// This is the main entry point for handling merge conflicts automatically.
// Returns true if the rebase and force-push succeeded, false otherwise.
func RebaseAndRetry(worktreePath, branchName, baseBranch string) bool {
	LogMsg(fmt.Sprintf("[auto-rebase] Attempting to rebase %s onto origin/%s", branchName, baseBranch))

	// Check if worktree exists
	if _, err := os.Stat(worktreePath); os.IsNotExist(err) {
		LogMsg(fmt.Sprintf("[auto-rebase] Worktree %s does not exist, cannot rebase", worktreePath))
		return false
	}

	// Attempt rebase
	rebaseResult := RebaseBranchOntoMain(worktreePath, branchName, baseBranch)
	if !rebaseResult.Success {
		if rebaseResult.HasConflicts {
			LogMsg("[auto-rebase] Rebase has conflicts that require manual resolution")
		} else {
			LogMsg(fmt.Sprintf("[auto-rebase] Rebase failed: %s", rebaseResult.Error))
		}
		return false
	}

	// Force push the rebased branch
	if err := ForcePushBranch(worktreePath, "origin", branchName); err != nil {
		LogMsg(fmt.Sprintf("[auto-rebase] Force push failed: %v", err))
		return false
	}

	LogMsg(fmt.Sprintf("[auto-rebase] Successfully rebased and pushed %s", branchName))
	return true
}

// RetryPRPendingMerges attempts to merge all issues that are in pr_pending state.
// Returns the number of issues successfully merged.
func RetryPRPendingMerges(cfg *RunConfig, state *StateManager) int {
	prPendingIssues := GetPRPendingIssues(cfg)
	if len(prPendingIssues) == 0 {
		return 0
	}

	merged := 0
	for _, issue := range prPendingIssues {
		branchName := issue.BranchName
		if branchName == "" {
			// Fallback: construct branch name from issue number
			repo, _ := cfg.PrimaryRepo()
			if repo != nil {
				branchName = repo.BranchPrefix + fmt.Sprintf("%d", issue.Number)
			}
		}
		if branchName == "" {
			continue
		}

		LogMsg(fmt.Sprintf("[pr-retry] Attempting to merge PR for issue #%d (branch: %s)", issue.Number, branchName))
		mergeResult := MergePRForIssue(issue.Number, branchName, cfg)

		if mergeResult.Success {
			// Mark as completed
			state.UpdateIssueStatus(issue.Number, "completed", nil)
			LogMsg(fmt.Sprintf("[pr-retry] Issue #%d merged successfully", issue.Number))
			merged++

			// Update epic checkbox if applicable
			if cfg.EpicNumber > 0 && cfg.EpicURL != "" {
				if err := UpdateEpicCheckbox(cfg.EpicURL, issue.Number, true); err != nil {
					LogMsg(fmt.Sprintf("WARNING: failed to update epic checkbox for #%d: %v", issue.Number, err))
				}
			}

			// Log completion
			GetActivityLogger().LogIssueCompleted(issue.Number, 0)
			if eb := GetGlobalEventBroadcaster(); eb != nil {
				eb.EmitIssueStatus(issue.Number, issue.Title, "completed", nil)
			}
		} else if mergeResult.Conflicts {
			// Merge conflict - need worker intervention
			LogMsg(fmt.Sprintf("[pr-retry] Issue #%d has merge conflicts, reverting to pending", issue.Number))
			if err := ReopenIssueForMergeConflict(issue.Number, branchName, mergeResult.MergeError, cfg); err != nil {
				LogMsg(fmt.Sprintf("WARNING: failed to reopen issue #%d: %v", issue.Number, err))
			}
			state.UpdateIssueStatus(issue.Number, "pending", nil)
			if eb := GetGlobalEventBroadcaster(); eb != nil {
				eb.EmitIssueStatus(issue.Number, issue.Title, "pending", nil)
			}
		} else {
			// Other merge error - keep as pr_pending for retry
			LogMsg(fmt.Sprintf("[pr-retry] Issue #%d merge failed (will retry): %s", issue.Number, mergeResult.MergeError))
		}
	}

	return merged
}

// CreateAndMergePR handles the full PR lifecycle for a completed issue:
// 1. Creates a PR if one doesn't exist
// 2. Attempts to merge the PR
// 3. If merge fails due to conflicts, attempts auto-rebase and retry
// 4. If auto-rebase fails, reopens the issue for worker resolution
// Returns the result of each step.
func CreateAndMergePR(issueNum int, issueTitle, branchName string, cfg *RunConfig, state *StateManager) PRLifecycleResult {
	// Use default worktree path pattern
	return CreateAndMergePRWithWorktree(issueNum, issueTitle, branchName, "", cfg, state)
}

// CreateAndMergePRWithWorktree handles the full PR lifecycle for a completed issue,
// with an optional explicit worktree path for auto-rebase.
// If worktreePath is empty, it will be inferred from the repo config.
func CreateAndMergePRWithWorktree(issueNum int, issueTitle, branchName, worktreePath string, cfg *RunConfig, state *StateManager) PRLifecycleResult {
	result := PRLifecycleResult{}

	// Get repo for worktree path (if not provided) and default branch
	repo, _ := cfg.PrimaryRepo()
	var baseBranch string
	if repo != nil {
		if worktreePath == "" {
			worktreePath = repo.WorktreeBase + "/issue-" + fmt.Sprintf("%d", issueNum)
		}
		baseBranch = repo.DefaultBranch
	}

	// Step 1: Create PR if needed
	prURL, err := CreatePRForIssue(issueNum, issueTitle, branchName, cfg)
	if err != nil {
		result.Error = fmt.Errorf("failed to create PR: %w", err)
		return result
	}
	if prURL != "" {
		result.PRCreated = true
		result.PRURL = prURL
		LogMsg(fmt.Sprintf("[pr-lifecycle] Created PR for #%d: %s", issueNum, prURL))
	}

	// Step 2: Attempt to merge
	mergeResult := MergePRForIssue(issueNum, branchName, cfg)
	if mergeResult.Success {
		result.Merged = true
		LogMsg(fmt.Sprintf("[pr-lifecycle] Merged PR for #%d", issueNum))
		return result
	}

	// Step 3: Handle merge failure
	if mergeResult.Conflicts {
		result.MergeConflict = true
		LogMsg(fmt.Sprintf("[pr-lifecycle] Merge conflict for #%d: %s", issueNum, mergeResult.MergeError))

		// Step 3a: Try auto-rebase
		if worktreePath != "" {
			result.RebaseAttempted = true
			LogMsg(fmt.Sprintf("[pr-lifecycle] Attempting auto-rebase for #%d", issueNum))

			if RebaseAndRetry(worktreePath, branchName, baseBranch) {
				result.RebaseSuccess = true
				LogMsg(fmt.Sprintf("[pr-lifecycle] Auto-rebase succeeded for #%d, retrying merge", issueNum))

				// Retry the merge after successful rebase
				retryResult := MergePRForIssue(issueNum, branchName, cfg)
				if retryResult.Success {
					result.Merged = true
					result.MergeConflict = false // Clear the conflict flag since we resolved it
					LogMsg(fmt.Sprintf("[pr-lifecycle] Merged PR for #%d after auto-rebase", issueNum))
					return result
				}

				// Merge still failed after rebase
				LogMsg(fmt.Sprintf("[pr-lifecycle] Merge still failed after rebase for #%d: %s", issueNum, retryResult.MergeError))
			} else {
				LogMsg(fmt.Sprintf("[pr-lifecycle] Auto-rebase failed for #%d, will reopen issue", issueNum))
			}
		}

		// Step 3b: Rebase failed or not possible - reopen issue for worker to resolve
		if err := ReopenIssueForMergeConflict(issueNum, branchName, mergeResult.MergeError, cfg); err != nil {
			result.Error = fmt.Errorf("failed to reopen issue: %w", err)
			return result
		}
		result.IssueReopened = true

		// Update issue status back to pending so a worker can pick it up
		if state != nil {
			state.UpdateIssueStatus(issueNum, "pending", nil)
			LogMsg(fmt.Sprintf("[pr-lifecycle] Reset issue #%d to pending for conflict resolution", issueNum))
		}
	} else if mergeResult.MergeError != "" {
		// Non-conflict merge error
		result.Error = fmt.Errorf("merge failed: %s", mergeResult.MergeError)
	}

	return result
}

