package orchestrator

import (
	"fmt"
	"os/exec"
	"strings"
)

// CreatePRForIssue creates a pull request for a completed issue.
// Returns the PR URL if created, empty string if PR already exists, error on failure.
func CreatePRForIssue(issueNum int, issueTitle, branchName string, cfg *RunConfig) (string, error) {
	repo, _ := cfg.PrimaryRepo()
	if repo == nil {
		return "", fmt.Errorf("no primary repo configured")
	}

	// Check if PR already exists for this branch
	checkCmd := exec.Command("gh", "pr", "list", "--head", branchName, "--json", "url", "-q", ".[0].url")
	checkCmd.Dir = repo.Path
	if out, err := checkCmd.Output(); err == nil && strings.TrimSpace(string(out)) != "" {
		// PR already exists
		return "", nil
	}

	// Build PR title and body
	title := fmt.Sprintf("%s (#%d)", issueTitle, issueNum)
	if len(title) > 70 {
		title = title[:67] + "..."
	}

	body := fmt.Sprintf(`## Summary

Closes #%d

## Changes

See commit history for details.

---
🤖 Generated by orchestrator
`, issueNum)

	// Create the PR
	cmd := exec.Command("gh", "pr", "create",
		"--title", title,
		"--body", body,
		"--head", branchName,
	)
	cmd.Dir = repo.Path
	out, err := cmd.CombinedOutput()
	if err != nil {
		// Check if it's just "no commits" error (branch already merged or doesn't exist)
		if strings.Contains(string(out), "already exists") ||
			strings.Contains(string(out), "No commits") {
			return "", nil
		}
		return "", fmt.Errorf("gh pr create: %v: %s", err, string(out))
	}

	// Extract PR URL from output
	prURL := strings.TrimSpace(string(out))
	return prURL, nil
}

// MergeResult represents the outcome of a PR merge attempt.
type MergeResult struct {
	Success    bool
	PRNumber   int
	MergeError string
	Conflicts  bool
}

// MergePRForIssue attempts to merge a PR for a completed issue.
// Returns merge result with details about success or failure.
func MergePRForIssue(issueNum int, branchName string, cfg *RunConfig) MergeResult {
	repo, _ := cfg.PrimaryRepo()
	if repo == nil {
		return MergeResult{Success: false, MergeError: "no primary repo configured"}
	}

	// Get PR number for this branch
	prNum, err := GetPRNumberForBranch(branchName, repo.Path)
	if err != nil {
		return MergeResult{Success: false, MergeError: fmt.Sprintf("failed to get PR number: %v", err)}
	}
	if prNum == 0 {
		return MergeResult{Success: false, MergeError: "no PR found for branch"}
	}

	// Attempt to merge with squash (don't use --delete-branch as it fails with worktrees)
	cmd := exec.Command("gh", "pr", "merge", fmt.Sprintf("%d", prNum), "--squash")
	cmd.Dir = repo.Path
	out, err := cmd.CombinedOutput()
	outStr := string(out)

	if err != nil {
		// Check for merge conflicts
		if strings.Contains(outStr, "not mergeable") ||
			strings.Contains(outStr, "merge conflict") ||
			strings.Contains(outStr, "cannot be cleanly created") {
			return MergeResult{
				Success:    false,
				PRNumber:   prNum,
				MergeError: outStr,
				Conflicts:  true,
			}
		}
		return MergeResult{
			Success:    false,
			PRNumber:   prNum,
			MergeError: fmt.Sprintf("gh pr merge: %v: %s", err, outStr),
		}
	}

	// Delete remote branch separately (local branch stays for worktree)
	delCmd := exec.Command("git", "push", "origin", "--delete", branchName)
	delCmd.Dir = repo.Path
	if delOut, delErr := delCmd.CombinedOutput(); delErr != nil {
		// Log but don't fail - merge succeeded
		LogMsg(fmt.Sprintf("[merge] Warning: failed to delete remote branch %s: %s", branchName, string(delOut)))
	}

	LogMsg(fmt.Sprintf("[merge] Successfully merged PR #%d for issue #%d", prNum, issueNum))
	return MergeResult{Success: true, PRNumber: prNum}
}

// GetPRNumberForBranch returns the PR number for a given branch.
func GetPRNumberForBranch(branchName, repoPath string) (int, error) {
	cmd := exec.Command("gh", "pr", "list", "--head", branchName, "--json", "number", "-q", ".[0].number")
	cmd.Dir = repoPath
	out, err := cmd.Output()
	if err != nil {
		return 0, err
	}

	numStr := strings.TrimSpace(string(out))
	if numStr == "" {
		return 0, nil
	}

	var num int
	_, err = fmt.Sscanf(numStr, "%d", &num)
	return num, err
}

// ReopenIssueForMergeConflict reopens an issue when its PR has merge conflicts.
// It adds a comment explaining the conflict and what needs to be done.
func ReopenIssueForMergeConflict(issueNum int, branchName string, mergeError string, cfg *RunConfig) error {
	repo, _ := cfg.PrimaryRepo()
	if repo == nil {
		return fmt.Errorf("no primary repo configured")
	}

	// Reopen the issue
	cmd := exec.Command("gh", "issue", "reopen", fmt.Sprintf("%d", issueNum))
	cmd.Dir = repo.Path
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to reopen issue: %v: %s", err, string(out))
	}

	// Add a comment explaining the merge conflict
	comment := fmt.Sprintf(`## Merge Conflict

The PR for this issue has merge conflicts and could not be automatically merged.

**Branch:** `+"`%s`"+`

**Error:**
`+"```"+`
%s
`+"```"+`

**Action Required:**
1. Rebase the branch onto main: `+"`git fetch origin && git rebase origin/main`"+`
2. Resolve any conflicts
3. Push the updated branch: `+"`git push --force-with-lease`"+`
4. The orchestrator will retry the merge

---
🤖 Generated by orchestrator`, branchName, mergeError)

	commentCmd := exec.Command("gh", "issue", "comment", fmt.Sprintf("%d", issueNum), "--body", comment)
	commentCmd.Dir = repo.Path
	if out, err := commentCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to add comment: %v: %s", err, string(out))
	}

	LogMsg(fmt.Sprintf("[merge] Reopened issue #%d due to merge conflicts", issueNum))
	return nil
}

// PRLifecycleResult represents the outcome of the full PR lifecycle.
type PRLifecycleResult struct {
	PRCreated     bool
	PRURL         string
	Merged        bool
	MergeConflict bool
	IssueReopened bool
	Error         error
}

// CreateAndMergePR handles the full PR lifecycle for a completed issue:
// 1. Creates a PR if one doesn't exist
// 2. Attempts to merge the PR
// 3. If merge fails due to conflicts, reopens the issue for worker resolution
// Returns the result of each step.
func CreateAndMergePR(issueNum int, issueTitle, branchName string, cfg *RunConfig, state *StateManager) PRLifecycleResult {
	result := PRLifecycleResult{}

	// Step 1: Create PR if needed
	prURL, err := CreatePRForIssue(issueNum, issueTitle, branchName, cfg)
	if err != nil {
		result.Error = fmt.Errorf("failed to create PR: %w", err)
		return result
	}
	if prURL != "" {
		result.PRCreated = true
		result.PRURL = prURL
		LogMsg(fmt.Sprintf("[pr-lifecycle] Created PR for #%d: %s", issueNum, prURL))
	}

	// Step 2: Attempt to merge
	mergeResult := MergePRForIssue(issueNum, branchName, cfg)
	if mergeResult.Success {
		result.Merged = true
		LogMsg(fmt.Sprintf("[pr-lifecycle] Merged PR for #%d", issueNum))
		return result
	}

	// Step 3: Handle merge failure
	if mergeResult.Conflicts {
		result.MergeConflict = true
		LogMsg(fmt.Sprintf("[pr-lifecycle] Merge conflict for #%d: %s", issueNum, mergeResult.MergeError))

		// Reopen the issue for worker to resolve
		if err := ReopenIssueForMergeConflict(issueNum, branchName, mergeResult.MergeError, cfg); err != nil {
			result.Error = fmt.Errorf("failed to reopen issue: %w", err)
			return result
		}
		result.IssueReopened = true

		// Update issue status back to pending so a worker can pick it up
		if state != nil {
			state.UpdateIssueStatus(issueNum, "pending", nil)
			LogMsg(fmt.Sprintf("[pr-lifecycle] Reset issue #%d to pending for conflict resolution", issueNum))
		}
	} else if mergeResult.MergeError != "" {
		// Non-conflict merge error
		result.Error = fmt.Errorf("merge failed: %s", mergeResult.MergeError)
	}

	return result
}

