package orchestrator

import (
	"fmt"
	"os/exec"
	"strings"
)

// CreatePRForIssue creates a pull request for a completed issue.
// Returns the PR URL if created, empty string if PR already exists, error on failure.
func CreatePRForIssue(issueNum int, issueTitle, branchName string, cfg *RunConfig) (string, error) {
	repo, _ := cfg.PrimaryRepo()
	if repo == nil {
		return "", fmt.Errorf("no primary repo configured")
	}

	// Check if PR already exists for this branch
	checkCmd := exec.Command("gh", "pr", "list", "--head", branchName, "--json", "url", "-q", ".[0].url")
	checkCmd.Dir = repo.Path
	if out, err := checkCmd.Output(); err == nil && strings.TrimSpace(string(out)) != "" {
		// PR already exists
		return "", nil
	}

	// Build PR title and body
	title := fmt.Sprintf("%s (#%d)", issueTitle, issueNum)
	if len(title) > 70 {
		title = title[:67] + "..."
	}

	body := fmt.Sprintf(`## Summary

Closes #%d

## Changes

See commit history for details.

---
🤖 Generated by orchestrator
`, issueNum)

	// Create the PR
	cmd := exec.Command("gh", "pr", "create",
		"--title", title,
		"--body", body,
		"--head", branchName,
	)
	cmd.Dir = repo.Path
	out, err := cmd.CombinedOutput()
	if err != nil {
		// Check if it's just "no commits" error (branch already merged or doesn't exist)
		if strings.Contains(string(out), "already exists") ||
			strings.Contains(string(out), "No commits") {
			return "", nil
		}
		return "", fmt.Errorf("gh pr create: %v: %s", err, string(out))
	}

	// Extract PR URL from output
	prURL := strings.TrimSpace(string(out))
	return prURL, nil
}

