"""Tests for the commenter module."""

import json
import subprocess
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from review.commenter import (
    GitHubClient,
    GitLabClient,
    format_review_comment,
    get_platform_client,
    post_review_comment,
)


class TestFormatReviewComment:
    """Tests for format_review_comment."""

    def test_formats_complete_review(self):
        """Format a review with all fields."""
        review = {
            "cycle": 2,
            "completeness": {
                "score": 8,
                "status": "Complete",
                "missing_elements": [],
            },
            "suitability": {
                "score": 7,
                "concerns": "May require external API access",
                "recommendation": "Add authentication details to scope",
            },
            "dependencies": {
                "blocks": [45, 46],
                "blocked_by": [40],
            },
        }

        result = format_review_comment(review)

        assert "## Orchestrator Review (Cycle 2)" in result
        assert "**Score**: 8/10" in result
        assert "**Status**: Complete" in result
        assert "**Missing Elements**: None" in result
        assert "**Score**: 7/10" in result
        assert "May require external API access" in result
        assert "Add authentication details to scope" in result
        assert "#45" in result
        assert "#46" in result
        assert "#40" in result
        assert "*Generated by Issue Review Orchestrator*" in result

    def test_formats_minimal_review(self):
        """Format a review with minimal fields."""
        review = {"cycle": 1}

        result = format_review_comment(review)

        assert "## Orchestrator Review (Cycle 1)" in result
        assert "**Score**: N/A/10" in result
        assert "**Status**: Unknown" in result

    def test_handles_missing_elements_list(self):
        """Format missing elements as comma-separated list."""
        review = {
            "cycle": 1,
            "completeness": {
                "score": 5,
                "status": "Incomplete",
                "missing_elements": ["Unit tests", "Documentation", "Error handling"],
            },
        }

        result = format_review_comment(review)

        assert "Unit tests, Documentation, Error handling" in result

    def test_handles_empty_dependencies(self):
        """Handle empty dependency lists."""
        review = {
            "cycle": 1,
            "dependencies": {
                "blocks": [],
                "blocked_by": [],
            },
        }

        result = format_review_comment(review)

        assert "Blocks: None" in result
        assert "Blocked by: None" in result

    def test_handles_string_missing_elements(self):
        """Handle missing_elements as string (not list)."""
        review = {
            "cycle": 1,
            "completeness": {
                "missing_elements": "Missing tests",
            },
        }

        result = format_review_comment(review)

        assert "Missing tests" in result


class TestGetPlatformClient:
    """Tests for get_platform_client."""

    def test_returns_github_client(self):
        """Get GitHub client."""
        client = get_platform_client("github", token="test-token")
        assert isinstance(client, GitHubClient)
        assert client.token == "test-token"

    def test_returns_gitlab_client(self):
        """Get GitLab client."""
        client = get_platform_client("gitlab", token="test-token")
        assert isinstance(client, GitLabClient)
        assert client.token == "test-token"

    def test_case_insensitive(self):
        """Platform name is case-insensitive."""
        assert isinstance(get_platform_client("GitHub"), GitHubClient)
        assert isinstance(get_platform_client("GITLAB"), GitLabClient)

    def test_unknown_platform_raises(self):
        """Unknown platform raises ValueError."""
        with pytest.raises(ValueError, match="Unknown platform"):
            get_platform_client("bitbucket")

    @patch.dict("os.environ", {"GITHUB_TOKEN": "env-token"})
    def test_uses_env_token(self):
        """Falls back to environment variable for token."""
        client = get_platform_client("github")
        assert client.token == "env-token"

    @patch.dict("os.environ", {"GITLAB_URL": "https://gitlab.example.com"})
    def test_gitlab_custom_url(self):
        """Uses GITLAB_URL environment variable."""
        client = get_platform_client("gitlab")
        assert client.base_url == "https://gitlab.example.com"


class TestGitHubClient:
    """Tests for GitHubClient."""

    def test_post_via_cli_success(self):
        """Successfully post via gh CLI."""
        client = GitHubClient()

        with patch("subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=0, stderr="")
            result = client._post_via_cli("owner/repo", 42, "Test comment")

        assert result is True
        mock_run.assert_called_once()
        args = mock_run.call_args[0][0]
        assert "gh" in args
        assert "issue" in args
        assert "comment" in args
        assert "42" in args
        assert "--repo" in args
        assert "owner/repo" in args

    def test_post_via_cli_failure(self):
        """Handle gh CLI failure."""
        client = GitHubClient(max_retries=1)

        with patch("subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=1, stderr="not authenticated")
            result = client._post_via_cli("owner/repo", 42, "Test comment")

        assert result is False

    def test_post_via_cli_not_found(self):
        """Handle missing gh CLI."""
        client = GitHubClient()

        with patch("subprocess.run", side_effect=FileNotFoundError):
            result = client._post_via_cli("owner/repo", 42, "Test comment")

        assert result is False

    def test_post_via_cli_rate_limit_retry(self):
        """Retry on rate limit."""
        client = GitHubClient(max_retries=2, retry_delay=0.01)

        call_count = [0]

        def mock_run(*args, **kwargs):
            call_count[0] += 1
            if call_count[0] == 1:
                return MagicMock(returncode=1, stderr="rate limit exceeded")
            return MagicMock(returncode=0, stderr="")

        with patch("subprocess.run", side_effect=mock_run):
            result = client._post_via_cli("owner/repo", 42, "Test comment")

        assert result is True
        assert call_count[0] == 2

    def test_post_comment_falls_back_to_api(self):
        """Falls back to API when CLI fails."""
        client = GitHubClient(token="test-token", max_retries=1)

        with patch.object(client, "_post_via_cli", return_value=False):
            with patch.object(client, "_post_via_api", return_value=True) as mock_api:
                result = client.post_comment("owner/repo", 42, "Test comment")

        assert result is True
        mock_api.assert_called_once()

    def test_post_comment_no_fallback_without_token(self):
        """No API fallback without token."""
        client = GitHubClient(token=None, max_retries=1)

        with patch.object(client, "_post_via_cli", return_value=False):
            result = client.post_comment("owner/repo", 42, "Test comment")

        assert result is False


class TestGitLabClient:
    """Tests for GitLabClient."""

    def test_post_via_cli_success(self):
        """Successfully post via glab CLI."""
        client = GitLabClient()

        with patch("subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=0, stderr="")
            result = client._post_via_cli("group/repo", 42, "Test comment")

        assert result is True
        mock_run.assert_called_once()
        args = mock_run.call_args[0][0]
        assert "glab" in args
        assert "issue" in args
        assert "comment" in args
        assert "--message" in args

    def test_post_via_cli_failure(self):
        """Handle glab CLI failure."""
        client = GitLabClient(max_retries=1)

        with patch("subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=1, stderr="not authenticated")
            result = client._post_via_cli("group/repo", 42, "Test comment")

        assert result is False

    def test_post_comment_falls_back_to_api(self):
        """Falls back to API when CLI fails."""
        client = GitLabClient(token="test-token", max_retries=1)

        with patch.object(client, "_post_via_cli", return_value=False):
            with patch.object(client, "_post_via_api", return_value=True) as mock_api:
                result = client.post_comment("group/repo", 42, "Test comment")

        assert result is True
        mock_api.assert_called_once()


class TestPostReviewComment:
    """Tests for post_review_comment."""

    def test_posts_to_github(self):
        """Post review to GitHub issue."""
        review = {"cycle": 1}

        with patch("review.commenter.get_platform_client") as mock_get_client:
            mock_client = MagicMock()
            mock_client.post_comment.return_value = True
            mock_get_client.return_value = mock_client

            result = post_review_comment("github", "owner/repo", 42, review)

        assert result is True
        mock_client.post_comment.assert_called_once()
        call_args = mock_client.post_comment.call_args
        assert call_args[0][0] == "owner/repo"
        assert call_args[0][1] == 42
        assert "Orchestrator Review" in call_args[0][2]

    def test_posts_to_gitlab(self):
        """Post review to GitLab issue."""
        review = {"cycle": 1}

        with patch("review.commenter.get_platform_client") as mock_get_client:
            mock_client = MagicMock()
            mock_client.post_comment.return_value = True
            mock_get_client.return_value = mock_client

            result = post_review_comment("gitlab", "group/repo", 42, review)

        assert result is True
        mock_get_client.assert_called_once_with("gitlab", None)

    def test_passes_token(self):
        """Pass token to client."""
        review = {"cycle": 1}

        with patch("review.commenter.get_platform_client") as mock_get_client:
            mock_client = MagicMock()
            mock_client.post_comment.return_value = True
            mock_get_client.return_value = mock_client

            post_review_comment("github", "owner/repo", 42, review, token="my-token")

        mock_get_client.assert_called_once_with("github", "my-token")

    def test_returns_false_on_failure(self):
        """Return False when posting fails."""
        review = {"cycle": 1}

        with patch("review.commenter.get_platform_client") as mock_get_client:
            mock_client = MagicMock()
            mock_client.post_comment.return_value = False
            mock_get_client.return_value = mock_client

            result = post_review_comment("github", "owner/repo", 42, review)

        assert result is False
